# Generated by Django 2.0.5 on 2018-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180606_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='closetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='opentime',
            field=models.DateTimeField(),
        ),
    ]
